apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - oew72229.diamond.ac.uk
  rules:
  - host: oew72229.diamond.ac.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-svc
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: nginx-svc-api
            port:
              number: 80
